// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJF5xls7fRCQYWgC26vWnkT9JAXqyAbsc',
    appId: '1:701907974947:web:a387dd33b5e6087521ea96',
    messagingSenderId: '701907974947',
    projectId: 'my-portfolio-2b16f',
    authDomain: 'my-portfolio-2b16f.firebaseapp.com',
    storageBucket: 'my-portfolio-2b16f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh1Ij2TvwDG63BV4lGJUaOdEIzac_QlWk',
    appId: '1:701907974947:android:a31c4459bf00644221ea96',
    messagingSenderId: '701907974947',
    projectId: 'my-portfolio-2b16f',
    storageBucket: 'my-portfolio-2b16f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALxe9Nz2TdeILglzBP2OC8W3IC20gUdm0',
    appId: '1:701907974947:ios:94fea5824e616dab21ea96',
    messagingSenderId: '701907974947',
    projectId: 'my-portfolio-2b16f',
    storageBucket: 'my-portfolio-2b16f.appspot.com',
    iosBundleId: 'com.example.portfolio2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALxe9Nz2TdeILglzBP2OC8W3IC20gUdm0',
    appId: '1:701907974947:ios:8b6f8087e865dcb921ea96',
    messagingSenderId: '701907974947',
    projectId: 'my-portfolio-2b16f',
    storageBucket: 'my-portfolio-2b16f.appspot.com',
    iosBundleId: 'com.example.portfolio2.RunnerTests',
  );
}
